### ISSUE TITLE
[1.4.4] System Exception HEROsModModWorld must override all of (SaveWorldData/LoadWorldData) or none

### ISSUE THREAD

**Issue by Setnour6** [JavidPack/HEROsMod#119]
Using Windows 11 on Steam on tModLoader 1.4.4 preview.

When loading HEROs Mod as usual, the mod doesn't load this time due to it being outdated, and also not overriding all of the world data to be saved or loaded, or none of the data.
![image](https://user-images.githubusercontent.com/70764728/230524478-b6202579-3190-400c-be48-0858ee1f644c.png)
![image](https://user-images.githubusercontent.com/70764728/230524558-4817089b-4261-472d-bf6e-baad0d2b4493.png)

To reproduce:
1. Enable HEROs Mod and reload
2. It fails to load.

In my case, I started up tModLoader and it happened to already be enabled. Loading failed unfortunately.

**Comment by JavidPack** [comment]
Fixed in v0.4.12.2
