### ISSUE TITLE
Misc. and Extensions button not working

### ISSUE THREAD

**Issue by SkyntfklyNrdy** [JavidPack/HEROsMod#12]
Every time I try to click on Misc. options or Extension tools it does nothing, tried the other buttons and it worked.

**Comment by thimbleofthe** [comment]
I have the same issue, and I have yet to find a fix

**Comment by thimbleofthe** [comment]
I found a fix! You need to keep the UI scale at 100%. If you change that it seems to mess it up. If you have enlarged the UI, simply go to settings in-game and change the UI scale to the smallest it can be.

**Comment by thimbleofthe** [comment]
Hope this helps
