### ISSUE TITLE
Zenith is not categorized as a weapon

### ISSUE THREAD

**Issue by Setnour6** [JavidPack/HEROsMod#126]
Duplicate but superior issue of  #108.

Going to get straight to the point:
Cheat Sheet has that categorized but HERO's Mod doesn't.
![image](https://github.com/JavidPack/HEROsMod/assets/70764728/b9eeee04-1ae9-43ee-97db-358e2eed3f25)

You can try to add Zenith as a category using some of the Recipe Browser / Cheat Sheet item listing code.
I'm not familiar with the listing code here yet but I'll see if I can contribute to the fixing of this issue, unless you want to do it first.

**Comment by JavidPack** [comment]
Fixed, not sure when.
