### ISSUE TITLE
Dedicated Server Connectivity Issue after 2 hours

### ISSUE THREAD

**Issue by Bartetho** [JavidPack/HEROsMod#22]
The problem is after certain period of time, players can't join the server. It says "invalid operation at this state" I removed other mods to see if heros mod is the problem, yeah seems like it. Also is it possible to add auto save option because i have to change it noon for my dedicated server to save the game.

**Comment by shminkie** [comment]
Confirmed. Same problem for me

**Comment by JavidPack** [comment]
Apparently no longer an issue.
