### ISSUE TITLE
Possible Fix For Server Locking Up With HERO's Mod

### ISSUE THREAD

**Issue by DoomFishWasTaken** [JavidPack/HEROsMod#23]
Found In Network.cs / On line 153
`FreezeNonLoggedInPlayers();`
Change to (should be like this):
`// FreezeNonLoggedInPlayers();`

**Comment by JavidPack** [comment]
Can you explain why this fixes the issue? From a glance it seems like it just disables the Freezed buff that is applied to users that aren't logged in.

**Comment by DoomFishYT** [comment]
Just ignore it it worked for a little while but then broke again
