### ISSUE TITLE
Disable Logins

### ISSUE THREAD

**Issue by MrDj200** [JavidPack/HEROsMod#25]
Hello, 
is it possible to disable logins? I play on a small private server and it gets annoying having to type in the credentials all the time. 
Is there any way to disable the login based system and authenticate via steam?

-Dj

**Comment by C0rn3j** [comment]
I'd very much like to see the logins become optional.

Just add an option to the settings not to freeze unconnected players.

Personally I only want to use the mod to disable gravestones.

**Comment by JavidPack** [comment]
Fixed in f6281ab85bfc6425f63e18f0c7950e6ef692307a
