### ISSUE TITLE
Add Support for ServerSideCharacter

### ISSUE THREAD

**Issue by dark22** [JavidPack/HEROsMod#27]
JavidPack and Hero, thank very much for maintaining the project available and opensource, this is a great and complete stuff for admins servers! 

Anyone could to implement support for ServerSideCharacter? It would be a very interesting addition, since it is already able to manage a server well as TShock already does on clients without mods.

**Comment by JavidPack** [comment]
There is a ServerSideCharacter mod called SSC you can download.
