### ISSUE TITLE
Tiny code change

### ISSUE THREAD

**Issue by KceGio** [JavidPack/HEROsMod#39]
Why is line 218 and 219 of [this file](https://github.com/JavidPack/HEROsMod/blob/master/UIKit/UIView.cs#L218) using a formula like this `children[children.Count - 1 - i]` instead of simply this `children[i]`

**Comment by JavidPack** [comment]
Dunno, probably because it's going backwards, maybe other code might remove elements in children, which would cause issues if iterating in order.
