### ISSUE TITLE
Log out and in apparently causes instant respawn

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/HEROsMod#59]
"i use better multiplayer mod. (it is during the multi people try boss hunt, some character dies no respawn) and my server manage use hero's mod. ... during the boss, click the logout button is resurrection."

**Comment by TheBambino** [comment]
This does not seem to be an issue with the latest Hero’s Mod & Better Muliplayer. I always use these two in conjunction.

**Comment by tieeeeen1994** [comment]
This is still an issue. With Hero's Mod on, anyone who is dead in a boss fight can instantly respawn when they log out and log back in. Is this a bug? Is there a fix around this?

**Comment by JavidPack** [comment]
I just released v0.4.14.3 which fixes this. Logging out no longer teleports/respawns, that doesn't seem to be useful in the first place so I removed it.

**Comment by tieeeeen1994** [comment]
Thank you!
