### ISSUE TITLE
Teleport on Map interfering with Pylon system

### ISSUE THREAD

**Issue by JavidPack** [JavidPack/HEROsMod#73]
Report from discord

**Comment by irondragon12** [comment]
how do i disable teleporting on map tho?

**Comment by JavidPack** [comment]
Unless you are in multiplayer and don't have the permission to teleport, there is no alternative for now.

**Comment by irondragon12** [comment]
damn it!! wait. so the "for now" means there will be a way in the future updates of this mod?

**Comment by JavidPack** [comment]
well, yeah, if I or anyone else gets around to updating the mod and fixing this issue somehow. That's why it is here in the issue tracker.

**Comment by irondragon12** [comment]
cool thanks

**Comment by JavidPack** [comment]
Also: ignore any click over any modmapmarker, since those have other uses?

**Comment by JavidPack** [comment]
TODO: Add toggle to draw fullscreen map, add check for mouse right down, should fix most issues and Ved_s request
