### ISSUE TITLE
[REQUEST] Buddha Mode Feature

### ISSUE THREAD

**Issue by RamenGuy** [JavidPack/HEROsMod#84]
Originally a debug function in Source games, Buddha Mode is a variation on God Mode that allows the player to take damage, but never die. Adding a function like this would be immensely helpful to mod testers, especially in situations where the ability to take damage is important (a specific example would be testing a boss fought with the Calamity Mod's Hydrothermic Armor, which has effects based on the player's health that could alter results.

**Comment by JavidPack** [comment]
I can see this being useful. I'm guessing if someone implements this, the easiest approach would be a right click on the invincibility icon to toggle the behavior.

**Comment by RamenGuy** [comment]
I've actually already modded it in, it allows you to be hurt until you reach below 120 hp, at which point it resets. (Meant to be used with max obtainable HP but I could make it work with lower.) Attacks which would instakill players are bypassed. If you want, I can send it on discord?

**Comment by JavidPack** [comment]
Sure, if you aren't familiar with making pull requests with git, you can just send it to me there.

**Comment by RamenGuy** [comment]
I can make a pull request tonight if needed, but I'd like you to review the code first if that's alright. It uses the same code as God mode, for the most part.

**Comment by JavidPack** [comment]
If you make a PR, I can directly make reviews and changes to your PR, if anything needs changing. If you'd rather I see it first privately, you can send it to me on discord too. It'd be a lot easier to keep track of the files changed and edits if we stick to git PR though. Whatever you want.

**Comment by RamenGuy** [comment]
Git PR works, i'll send it in a few hours.
